wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    code_path: code/train_translation.py
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 2
      4: 3.7.11
      5: 0.10.31
      6: 4.14.1
      8:
      - 8
batch_size:
  desc: null
  value: 16
betas:
  desc: null
  value:
  - 0.9
  - 0.98
checkbleu:
  desc: null
  value: 5
checkpoint_dir:
  desc: null
  value: checkpoint
clip:
  desc: null
  value: 1
dfeedforward:
  desc: null
  value: 200
dist_url:
  desc: null
  value: tcp://localhost:58472
dmodel:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 5
eps:
  desc: null
  value: 1.0e-09
learning_rate:
  desc: null
  value: 0.2
load:
  desc: null
  value: 0
loss_fn:
  desc: null
  value: cross_entropy
mbert_out_size:
  desc: null
  value: 768
momentum:
  desc: null
  value: 0.9
ngpus_per_node:
  desc: null
  value: 2
nhead:
  desc: null
  value: 4
nlayers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: adam
print_freq:
  desc: null
  value: 5
projector:
  desc: null
  value: 768-256
rank:
  desc: null
  value: 0
test_translation:
  desc: null
  value: 0
tokenizer:
  desc: null
  value: bert-base-multilingual-uncased
train:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 1.0e-06
workers:
  desc: null
  value: 4
world_size:
  desc: null
  value: 2
