program: train_translation.py
method: bayes
metric: 
    name: epoch_loss
    goal: minimize

description: 'translation sweep' 
parameters: 

    epochs:
        distribution: 'q_uniform'
        min: 10
        max: 40
        q: 4

    batch_size: 
        values: [16, 32, 64, 128, 256]
    
    nhead:
        distribution: 'q_uniform'
        min: 2
        max: 8
        q: 2

    dfeedforward:
        values: [ 256, 512, 1024]

    nlayers:
        distribution: 'q_uniform'
        min: 2
        max: 6
        q: 2

    
 # to add: lr, dropout, betas, loss_fn  


