wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1647488054
    t:
      1:
      - 1
      - 11
      3:
      - 16
      4: 3.7.11
      5: 0.12.9
      6: 4.15.0
      8:
      - 3
      - 8
batch_size:
  desc: null
  value: 64
betas:
  desc: null
  value:
  - 0.9
  - 0.98
checkpoint_dir:
  desc: null
  value: checkpoint
clip:
  desc: null
  value: 1
dfeedforward:
  desc: null
  value: 256
dist_url:
  desc: null
  value: tcp://localhost:58472
dmodel:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 2
eps:
  desc: null
  value: 1.0e-09
learning_rate:
  desc: null
  value: 0.2
loss_fn:
  desc: null
  value: cross_entropy
mbert_out_size:
  desc: null
  value: 768
ngpus_per_node:
  desc: null
  value: 1
nhead:
  desc: null
  value: 3
nlayers:
  desc: null
  value: 3
rank:
  desc: null
  value: 0
tokenizer:
  desc: null
  value: bert-base-multilingual-cased
weight_decay:
  desc: null
  value: 1.0e-06
workers:
  desc: null
  value: 20
world_size:
  desc: null
  value: 1
